### ISSUE TITLE
Samples for Reporting into Google Apps Scripts

### ISSUE THREAD

**Issue by yagihashib** [googleads/googleads-dfa-reporting-samples#10]
I'm working on importing DCM reports into Google sheets via Google Apps Scripts . There are a few examples on integration with DoubleClick trafficking with App Scripts, but none for the reporting piece.

https://developers.google.com/apps-script/advanced/doubleclick-campaigns

Would it be possible to get some more GS samples for reporting/DCM in general?

**Comment by jimper** [comment]
Hi there,

Is there something specific you're looking for? I don't think we'll be adding a full Apps Script sample set anytime soon, since it's usually pretty easy to adapt samples from other languages to Apps Script (Python is a good starting point). However, if there are things not sufficiently covered by other languages, we may consider adding more one-off samples like the ones you linked to.

You can also find some Apps Script snippets that other users have posted if you search on [our forum](https://developers.google.com/doubleclick-advertisers/community).

Regards,
-Jonathon Imperiosi, DCM API Team

**Comment by yagihashib** [comment]
Hey John,

Sorry, after thinking about it a bit this suggestion might be more geared towards the Google Sheets/Apps scripts API team. My pain points are with populating the Google Sheets columns, but here's my sample flow:

1. Create DCM report with specified dimensions 
2. Add GS code to pull run report (minus the report headers) and clone in Google sheets.
3. Add a trigger to run code every week.

I'll look into this more on my own since I think I can figure it out from the Python samples and Sheets samples, but maybe a one-off sample to pull a few report values into Google sheets via GS would help?

Thanks!
-Brandon

**Comment by jimper** [comment]
Hey Brandon,

As luck would have it, I do have some test code lying around that you might find useful. Beware, though, that I wrote this a long time ago and it hasn't been run in a while, so it may need a little massaging :)

```Javascript
function downloadReport(reportId, fileId) {
  var file = DcmApp.Files.get(reportId, fileId);
  
  if(file.urls) {
    var httpOptions = {
        'headers': {'Authorization': 'Bearer ' + ScriptApp.getOAuthToken()}
    }
    
    var contents = UrlFetchApp.fetch(file.urls.apiUrl, httpOptions);
    
    if(file.format == 'CSV') {
      createSpreadsheet(contents.getContentText(), file.fileName);
    } else {
      // Store the Excel file directly
      DocsList.createFile(contents.getBlob()).rename(file.fileName)
    }
  }
}

function createSpreadsheet(csvContent, fileName) {
  var rows = Utilities.parseCsv(csvContent);
      
  if(rows && rows.length) {
    // Create a new spreadshet using the specified filename
    var spreadSheet = SpreadsheetApp.create(fileName);
    var sheet = spreadSheet.getActiveSheet();
    
    // Output the result rows
    rows.map(function(r) { sheet.appendRow(r); });
  }
}
```

It shouldn't be too difficult to add a little logic into createSpreadsheet to strip out header and total rows, if that's something you'd like to do.

Regards,
-Jonathon Imperiosi, DCM API Team

**Comment by yagihashib** [comment]
Awesome, exactly what I'm looking for. Thank you!
