### ISSUE TITLE
DFA reporting - Exclude summary rows

### ISSUE THREAD

**Issue by phil-brainlabs** [googleads/googleads-dfa-reporting-samples#11]
Is it (going to be) possible when constructing and downloading a report via the API to exclude the summary rows at the top of a report eg.

> Report Title
> 		
> Date/Time Generated	1/11/17 14:57	
> Report Time Zone	Europe/London	
> Account ID	9433	
> Date Range	1/1/17 - 1/11/17	
> Campaign ID	Equals:1111116	
> Campaign ID	Equals:1111115	
> Campaign ID	Equals:1111114	
> Campaign ID	Equals:1111113	
> Campaign ID	Equals:1111112	
> MRC Accredited Metrics	Impressions(Desktop Display and Rich Media, Desktop Video, Mobile Video)	
> 		
> Report Fields

Would be nice if I didn't have to manually parse these fields out before getting to the data.

Thanks!

**Comment by jimper** [comment]
Hi there,

There aren't currently any plans to add this functionality to the API, but I'll pass your feedback on to the team here for consideration. If such an option is added in the future, you can expect to see an announcement on our [official communication channels](https://developers.google.com/doubleclick-advertisers/guides/migration#stay_informed).

Regards,
-- Jonathon Imperiosi, DCM API Team
