### ISSUE TITLE
DCM Reporting CSV Output Includes meta data

### ISSUE THREAD

**Issue by tspicer** [googleads/googleads-dfa-reporting-samples#12]
When downloading CSV Reports via the API there is meta-data about the report included in the output. This output can be variable based on the number of advertiser accounts included. For example:

```
Date/Time Generated,4/12/17 11:13 AM
Report Time Zone,America/New_York
Account ID,4444
Date Range,4/12/15 - 4/11/17
Advertiser,Equals:AZ - Foo-A (111111111)
Advertiser,Equals:AZ - Foo-C (2222222)
Advertiser,Equals:AZ - Foo-B (3333333)
Advertiser,Date,Site (DCM),Campaign,Creative,Placement,Campaign ID,Designated Market Area (DMA),Click-through URL,Impressions,Clicks,Active View: Viewable Impressions,Active View: Measurable Impressions,Video Views,Video Plays,Video Completions
```
Ideally we would like to only have the header row and then the data. Inclusion of the meta-data creates complexity in automating the processing of this data because of the variability of the included data. 

I might be missing something in the DCM UI or the API to not include this data. Any suggestions?

**Comment by jimper** [comment]
Hello,

Unfortunately it's not possible to generate report files without these headers. You'll need to implement your own logic to filter them out if your workflow requires it. The "Report Fields" row can help you determine when the header ends and report contents begin.

Regards,
- Jonathon Imperiosi, DCM API Team
