### ISSUE TITLE
insert new conversion for Doubleclick search

### ISSUE THREAD

**Issue by jyoo23** [googleads/googleads-dfa-reporting-samples#13]
Hi, 
I'm trying to upload new conversions through doulbleclick search but could not find Git sample and ended up here.
Could you verify my questions or point me to DS samples?

In this documentation, click ID is combination of gclid and gclsrc. 
https://developers.google.com/doubleclick-search/v2/how-tos/conversions/
But in this code snippet, it looks like just gclid, https://developers.google.com/doubleclick-search/v2/how-tos/conversions/insert
What's the correct ID format that we can use?

**Comment by jimper** [comment]
Hi there,

Unfortunately I'm not familiar with the DS API, so I can't give an authoritative answer. However, "Google Click ID" generally refers to the value of the gclid= parameter _only_. I would be surprised if it meant something different here, but recommend checking with the [DS support team](https://developers.google.com/doubleclick-search/v2/troubleshooting) to be sure.

Regards,
- Jonathon Imperiosi, DCM API Team
