### ISSUE TITLE
httperror 403 insufficient permissions in v3.0

### ISSUE THREAD

**Issue by razadera** [googleads/googleads-dfa-reporting-samples#16]
Hello,

I upgraded to v3.0 from 2.7 and am being presented with the following error when I try to run a report any report: 
HttpError 403 when requesting https:www.googleapis.com/dfareporting/v3.0/userprofiles?alt=json returned "Insufficient Permission"

I'm using Python 3.6.2 on a Debian Linux VM. I have created the client_secrets.json file and have saved it in the same directory as the sample files. Additionally, all three scopes (dfareporting, dfatrafficking, ddmconversions) are in the dfareporting_utils.py file. 

Thanks.

**Comment by jimper** [comment]
Hi there,

That error does normally indicate a missing scope. It's possible that you're using cached credentials which are missing the necessary reporting scope. To test this, you can delete any cached credentials (stored in a dfareporting.dat file) and rerun your application. This should launch a browser window and step you through the authorization process again, using the scopes listed in dfareporting_utils.py.

If you don't have a dfareporting.dat file or if you aren't presented with a browser window, you may have application default credentials configured which are being used mistakenly. To test this, you can comment out [this line](https://github.com/googleads/googleads-dfa-reporting-samples/blob/master/python/v3_0/dfareporting_utils.py#L116) to disable application default credential lookup and force the util to use the cleint_secrets.json file you're providing.

Regards,
-- Jonathon Imperiosi, DCM API Team

**Comment by razadera** [comment]
Hi jimper, 

Thanks for the quick reply! I was having that exact error where I wasn't presented with a new browser window to authenticate. After commenting out the line, I was presented with the error "local variable "credentials" referenced before assignment" so I just assigned credentials = None and everything worked out. 

Thanks again!

**Comment by matsuzaka-ryo** [comment]
Hi, @razadera @jimper 
I have the same issue with v4 api.
I read your discussion but I cannot find the solution.

My questions are:  

1.  
Where is [this line](https://github.com/googleads/googleads-dfa-reporting-samples/blob/master/python/v3_0/dfareporting_utils.py#L116)?
This link is no longer available.


2. Where `credentials = None` is located in codes?

```
~/googleads-dfa-reporting-samples/python/v4$ python download_file.py 123456789 0987654321
Traceback (most recent call last):
  File "/home/ryo/googleads-dfa-reporting-samples/python/v4/download_file.py", line 91, in <module>
    main(sys.argv)
  File "/home/ryo/googleads-dfa-reporting-samples/python/v4/download_file.py", line 55, in main
    fileId=file_id).execute()
                    ^^^^^^^^^
  File "/home/ryo/.cache/pypoetry/virtualenvs/googleads-dfa-reporting-samples-aytjwM6s-py3.11/lib/python3.11/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryo/.cache/pypoetry/virtualenvs/googleads-dfa-reporting-samples-aytjwM6s-py3.11/lib/python3.11/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://dfareporting.googleapis.com/dfareporting/v4/reports/123456789 /files/0987654321?alt=json returned "Request had insufficient authentication scopes.". Details: "[{'message': 'Insufficient Permission', 'domain': 'global', 'reason': 'insufficientPermissions'}]">
```

**Comment by matsuzaka-ryo** [comment]
I could solve my issue by myself.
