### ISSUE TITLE
DCM not updated when pushing a new Landingpage

### ISSUE THREAD

**Issue by J3remyD** [googleads/googleads-dfa-reporting-samples#17]
Hi there,

I'm trying to change the default landing page of a campaign by API with the following version : v3.1-rev1-1.23.0. I've created my campaign in DCM then I create a default landing page for the campaign's advertiser and I set it as default LP for the campaign, then I'm able to read my information properly. 
After that I want to change the LP's information, but I have a constraints in my software saying I want to create a new default LP instead to replace the previous one not just updating the existing one so I do : 

LandingPage landingPage = new LandingPage();
landingPage.setAdvertiserId(advId);
landingPage.setName(pageName);
landingPage.setUrl(newUrl);
reporting.advertiserLandingPages().insert(profileId, landingPage).execute();

Informations are well updated in my front, I have the brand new created LP informations and ID's from the API, but when I open the campaign in DCM directly it doesn't show me the new LP but the previous one, even though the changelog has taken my modifications into account....

I've attached a screenshot showing my problem. Hope you'll be able to help me out.

Cheers,
Jeremy

![dcm-issue](https://user-images.githubusercontent.com/13484476/41109850-4690e882-6a78-11e8-89c8-f04dfa4fa1f9.png)

**Comment by jimper** [comment]
Hi Jeremy,

This isn't a problem with your code, we've actually had similar reports of this happening from other users. The team here is investigating.

As this isn't a problem with the samples I'm going to close the issue for now. If you haven't already, please post about this over on the [API support forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-advertisers-api) and the support agents there will be able to provide you with updates.

Regards,
\- Jonathon Imperiosi, DCM API Team
