### ISSUE TITLE
EventTagOverrides is null but can view event tags in the DCM UI

### ISSUE THREAD

**Issue by nlokare** [googleads/googleads-dfa-reporting-samples#18]
Hi, I am using v3.2 of the API to request ads by campaign ID and placement ID. When I receive a response from the API, I noticed that none of the `Ad` response objects have an `eventTagOverrides` property. It appears that the `getEventTagOverrides` method returns null. However, I can verify that I have Event Tags enabled for the ad within the UI. Any help would be greatly appreciated. Thanks.

**Comment by jimper** [comment]
Hi there,

First check to see if the data you're looking for is in the [defaultClickThroughEventTagProperties](https://developers.google.com/doubleclick-advertisers/v3.2/ads#defaultClickThroughEventTagProperties) field instead. If not, please post on the [API support forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-advertisers-api) with details of the specific ads you're having issues with.

Regards,
\- Jonathon Imperiosi, DCM API Team
