### ISSUE TITLE
Upload offline conversions with DCLID

### ISSUE THREAD

**Issue by odedsh3** [googleads/googleads-dfa-reporting-samples#19]
Is it possible to upload offline conversions to CM with DCLID like I do with GCLID?

**Comment by jimper** [comment]
Hi there,

No, this isn't currently supported. See the [conversions overview guide](https://developers.google.com/doubleclick-advertisers/guides/conversions_overview#obtain_click_device_and_user_ids) for info on all supported identifiers. If you have any other API questions unrelated to code samples, please follow up on the [API support forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-advertisers-api).

Regards,
\- Jonathon Imperiosi, DCM API Team
