### ISSUE TITLE
DCM Update REAC report to custom date range

### ISSUE THREAD

**Issue by SandeepMT** [googleads/googleads-dfa-reporting-samples#21]
Hi Team,

Creating report is fine. But could you please suggest me steps to update custom date range for REACH report types in python.

**Comment by jimper** [comment]
Hi there,

I recommend reviewing our guide on [creating and updating reports](https://developers.google.com/doubleclick-advertisers/guides/create_reports). The first section covers options and steps needed to update an existing report. The second section has examples of specifying a custom date range as well as assigning values to an existing criteria. If you have any other general questions about working with reports in the API, please reach out to our [support team](https://developers.google.com/doubleclick-advertisers/get-support).

Regards,
\- Jonathon Imperiosi, DCM API Team
