### ISSUE TITLE
Setting read-only field Id for Size Object in CreatePlacement.java

### ISSUE THREAD

**Issue by yougaindra** [googleads/googleads-dfa-reporting-samples#23]
According to : https://developers.google.com/doubleclick-advertisers/v3.3/sizes#resource
>ID of this size. This is a read-only, auto-generated field.

but in CreatePlacement.java, it is being set
```
Size size = new Size();
size.setId(sizeId);
```

Is this required? If yes Why?

**Comment by jimper** [comment]
Hey there,

You're right, that ID is read-only. But that only applies when you're inserting, patching, or updating a Size object.

The CreatePlacement example isn't inserting a new Size or update an existing one. What that code is doing is creating a reference an existing Size object. If you wanted, you could retrieve the existing object by calling either Sizes.get() or Sizes.list() and use that instead.

\- Jonathon Imperiosi
