### ISSUE TITLE
examples for DCM/DFA Reporting and Trafficking API 

### ISSUE THREAD

**Issue by zhihong** [googleads/googleads-dfa-reporting-samples#3]
Hi, support team, 

May I know can you provide some examples for the new DCM/DFA v2.0 API?

Thanks 
Zhihong

**Comment by jimper** [comment]
Hey Zhihong,

Just FYI that PHP samples are up next now that the C# samples are done. If you have any questions in the meantime, feel free to ask over on the [forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-advertisers-api).

\- Jonathon

**Comment by zhihong** [comment]
Hi, Jimper,

Thanks for your update. 

Zhihong

**Comment by jimper** [comment]
PHP samples for v2.0 are now available.
