### ISSUE TITLE
Finding Profile ID

### ISSUE THREAD

**Issue by Gitzman** [googleads/googleads-dfa-reporting-samples#5]
Where is the Profile ID meant to be inserted in the Command Line call to create_report.py?

**Comment by jimper** [comment]
Profile ID is the first positional argument expected by every sample (except for ones that don't require a profile ID). Also be aware that you can use the -h flag to get detailed usage info for any sample, if you're ever not sure what values need to be specified or in what order:

```
python create_report.py -h

usage: create_report.py [-h] [--auth_host_name AUTH_HOST_NAME]
                        [--noauth_local_webserver]
                        [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
                        [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
                        profile_id

This example illustrates how to create a report.

positional arguments:
  profile_id            The ID of the profile to create a report for

optional arguments:
  -h, --help            show this help message and exit
  --auth_host_name AUTH_HOST_NAME
                        Hostname when running a local web server.
  --noauth_local_webserver
                        Do not run a local web server.
  --auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]
                        Port web server should listen on.
  --logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}
                        Set the logging level of detail.
```

**Comment by Gitzman** [comment]
Sorry, I meant where I can find the Profile ID.  In case others have this trouble, I found mine using the API explorer on this page.  

https://developers.google.com/doubleclick-advertisers/reporting/v2.5/userProfiles/list#try-it

**Comment by jimper** [comment]
Ah, sorry for the confusion. The [get_userprofiles.py](https://github.com/googleads/googleads-dfa-reporting-samples/blob/master/python/v2.4/get_userprofiles.py) sample can also be used to look up profile IDs, for folks running without access to a browser.
