### ISSUE TITLE
Double request in python

### ISSUE THREAD

**Issue by flyingsriracha** [googleads/googleads-dfa-reporting-samples#6]
Hi is it possible to construct two different request in one try statement?
example:
try:
    # Construct the request.
    request = service.placements().list(profileId=profile_id, maxStartDate=time.strftime("%Y-%m-%d"), minStartDate='2016-05-01')
    request = service.campaigns().list(profileId=profile_id)

**Comment by jimper** [comment]
Sure, we have a few examples that do that ([create_placement.py](https://github.com/googleads/googleads-dfa-reporting-samples/blob/master/python/v2.5/create_placement.py), for example). The try statements are only included in the samples to catch common errors.
