### ISSUE TITLE
How to use authenticate using service account

### ISSUE THREAD

**Issue by rahulsingh303** [googleads/googleads-dfa-reporting-samples#9]
Can anyone explain how to use authenticate using service account ? How this need to be called for say , with create_report.py ?

-Rahul

**Comment by jimper** [comment]
Hi Rahul,

There's a [service account example](https://github.com/googleads/googleads-dfa-reporting-samples/blob/master/python/v2.6/authenticate_using_service_account.py) included in the Python sample set that covers this. You should also read through [this guide](https://developers.google.com/doubleclick-advertisers/service_accounts) and ensure you've completed all the prerequisite steps. If you have any other questions about working with service accounts feel free to ask on our [support forum](https://developers.google.com/doubleclick-advertisers/community).

Regards,
-Jonathon Imperiosi, DCM API Team
